generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Customer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          customer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:
          label: Member since
      list:
        display: [=email, created_at]
        object_actions:
          delete: ~
      filter:  ~
      form:
        display: [email]
      edit:    ~
      new:     ~
