page:
  class: sfDoctrineRouteCollection
  options:
    model:                Page
    module:               pages
    prefix_path:          /pages
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: pages, action: index }