hoster:
  class: sfDoctrineRouteCollection
  options:
    model:                Hoster
    module:               hosters
    prefix_path:          /hosters
    column:               id
    with_wildcard_routes: true

server:
  class: sfDoctrineRouteCollection
  options:
    model:                Server
    module:               servers
    prefix_path:          /servers
    column:               id
    with_wildcard_routes: true

customer:
  class: sfDoctrineRouteCollection
  options:
    model:                Customer
    module:               customers
    prefix_path:          /customers
    column:               id
    with_wildcard_routes: true

page:
  class: sfDoctrineRouteCollection
  options:
    model:                Page
    module:               pages
    prefix_path:          /pages
    column:               id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: pages, action: index }