<?php

/**
 * BlogpostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogpostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogpostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Blogpost');
    }
}