<?php

/**
 * CustomerGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerGroup');
    }
}