<?php

/**
 * HosterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HosterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HosterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hoster');
    }
}