<?php

/**
 * RadacctTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadacctTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadacctTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radacct');
    }
}