<?php

/**
 * RadcheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadcheckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadcheckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radcheck');
    }
}