<?php

/**
 * RadgroupcheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadgroupcheckTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadgroupcheckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radgroupcheck');
    }
}