<?php

/**
 * RadgroupreplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadgroupreplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadgroupreplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radgroupreply');
    }
}