<?php

/**
 * RadipTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadipTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadipTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radip');
    }
}