<?php

/**
 * RadusergroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadusergroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadusergroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radusergroup');
    }
}