<?php

/**
 * ServerTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Server');
    }

    public function construct()
    {
      $this->addNamedQuery('unlimited', $this->createQuery('s')->where('transfer IS NULL'));
    }
}