<?php

/**
 * Server
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    anonvpn.com
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Server extends BaseServer
{
  public function setHostname($hostname)
  {
    $ip = gethostbyname($hostname);
    if ($ip !== $hostname)
    {
      $this->_set('ip', $ip);
    }
    else
    {
      throw new RuntimeException('Could not resolve ' . $hostname);
    }

    return $this->_set('hostname', $hostname);
  }

  public function setIp($ip)
  {
    throw new RuntimeException('Cannot directly set ip address. Set hostname instead.');
  }
}