all:
  sfSimpleGoogleSitemap:
    urls:
      homepage:
        url:      http://www.anonvpn.com/
        freq:     daily
        priority: 1.0
      servers:
        url:      http://www.anonvpn.com/vpn-servers-list.html
        freq:     daily
        priority: 1.0
      help:
        url:      http://www.anonvpn.com/help.html
        freq:     daily
        priority: 1.0