servers:
  url: /vpn-servers-list.html
  param: { module: servers, action: index }

help:
  url: /help.html
  param: { module: help, action: index }

checkout_approved:
  url: /checkout/approved
  param: { module: checkout, action: approved }

homepage:
  url:   /
  param: { module: static, action: home }