servers:
  url: /vpn-servers-list.html
  param: { module: servers, action: index }

help:
  url: /help.html
  param: { module: help, action: index }

checkout_unlimited:
  url: /buy-unlimited-vpn.html
  param: { module: checkout, action: unlimited }

checkout_approved:
  url: /checkout/approved
  param: { module: checkout, action: approved }

sitemap_xml:
  url: /sitemap.xml
  param: { module: sfSimpleGoogleSitemap, action: index }

homepage:
  url:   /
  param: { module: static, action: home }