Radcheck:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    email:
      type: string(64)
      notnull: true
    attr:
      type: string(64)
      notnull: true
      default: 'Cleartext-Password'
    op:
      type: char(2)
      default: ':='
      notnull: true
    value:
      type: string(253)
      notnull: true
  relations:
    Customer:
      class: Customer
      local: email
      foreign: email
      foreignAlias: Radchecks
      onDelete: CASCADE
      onUpdate: CASCADE