Radcheck:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    customer_id:
      type: integer(2)
      unsigned: true
      notnull: true
    attr:
      type: string(64)
      notnull: true
      default: 'Cleartext-Password'
    op:
      type: enum
      values: [':=', '==', '+=', '!=', '>', '>=', '<', '<=', '=~', '!~', '=*', '!*']
      default: ':='
      notnull: true
    value:
      type: string(253)
      notnull: true
  relations:
    Customer:
      class: Customer
      local: customer_id
      foreign: id
      foreignAlias: Radchecks
      onDelete: CASCADE
      onUpdate: CASCADE