Radgroupcheck:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    group_name:
      type: string(16)
      notnull: true
    attr:
      type: string(64)
      notnull: true
    op:
      type: enum
      values: [':=', '==', '+=', '!=', '>', '>=', '<', '<=', '=~', '!~', '=*', '!*']
      default: ':='
      notnull: true
    value:
      type: string(253)
      notnull: true
  relations:
    Group:
      local: group_name
      foreign: name
      foreignAlias: Radgroupchecks
      onDelete: CASCADE
      onUpdate: CASCADE