<?php

/**
 * BasesfCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property char $alpha2
 * @property char $alpha3
 * @property integer $numeric
 * @property string $name
 * 
 * @method char      getAlpha2()  Returns the current record's "alpha2" value
 * @method char      getAlpha3()  Returns the current record's "alpha3" value
 * @method integer   getNumeric() Returns the current record's "numeric" value
 * @method string    getName()    Returns the current record's "name" value
 * @method sfCountry setAlpha2()  Sets the current record's "alpha2" value
 * @method sfCountry setAlpha3()  Sets the current record's "alpha3" value
 * @method sfCountry setNumeric() Sets the current record's "numeric" value
 * @method sfCountry setName()    Sets the current record's "name" value
 * 
 * @package    anonvpn.com
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_country');
        $this->hasColumn('alpha2', 'char', 2, array(
             'type' => 'char',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('alpha3', 'char', 3, array(
             'type' => 'char',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('numeric', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));


        $this->index('codes', array(
             'fields' => 
             array(
              0 => 'alpha2',
              1 => 'alpha3',
              2 => 'numeric',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}