all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=anonvpncom
      username: root
      password:
      attributes:
        use_native_enum: true
        quote_identifier: true