<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('order', 'created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
        $this->addIndex('order', 'status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->addIndex('order', 'time', array(
             'fields' => 
             array(
              0 => 'created_at',
              1 => 'updated_at',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('order', 'created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
        $this->removeIndex('order', 'status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->removeIndex('order', 'time', array(
             'fields' => 
             array(
              0 => 'created_at',
              1 => 'updated_at',
             ),
             ));
    }
}