<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_country', array(
             'alpha2' => 
             array(
              'type' => 'char',
              'primary' => '1',
              'length' => '2',
             ),
             'alpha3' => 
             array(
              'type' => 'char',
              'notnull' => '1',
              'length' => '3',
             ),
             'numeric' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'notnull' => '1',
              'length' => '2',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '64',
             ),
             ), array(
             'indexes' => 
             array(
              'codes' => 
              array(
              'fields' => 
              array(
               0 => 'alpha2',
               1 => 'alpha3',
               2 => 'numeric',
              ),
              'unique' => '1',
              ),
             ),
             'primary' => 
             array(
              0 => 'alpha2',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('sf_country');
    }
}