<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('server', 'country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
        $this->createForeignKey('server', 'server_country_sf_country_alpha2', array(
             'name' => 'server_country_sf_country_alpha2',
             'local' => 'country',
             'foreign' => 'alpha2',
             'foreignTable' => 'sf_country',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('server', 'server_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('server', 'country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
        $this->dropForeignKey('server', 'server_country_sf_country_alpha2');
        $this->removeIndex('server', 'server_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
    }
}