<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'pending',
              1 => 'approved',
              2 => 'declined',
              3 => 'refund',
             ),
             'notnull' => '1',
             'default' => 'pending',
             ));
        $this->addColumn('order', 'updated_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('order', 'status');
        $this->removeColumn('order', 'updated_at');
    }
}