# radius uses this table
Customer:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    email:
      type: string(64)
      notnull: true
      unique: true