# radius uses this table
Customer:
  columns:
    # TODO: subject of rename to "email"
    username:
      type: string(64)
      notnull: true
      primary: true
      comment: "Unique email; primary key"
    attr:
      type: string(64)
      notnull: true
      default: 'Cleartext-Password'
    op:
      type: char(2)
      default: ':='
      notnull: true
    value:
      type: string(253)
      notnull: true