# radius uses this table
Customer:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    email:
      type: string(64)
      notnull: true
      primary: true
      comment: "Unique email; primary key"
