Ip:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
    pool_name:
      type: string(32)
      notnull: true
      default: 'default'
    subnet:
      type: integer(1)
      unsigned: true
      notnull: true
    ip:
      type: integer(1)
      unsigned: true
      notnull: true
    customer_id:
      type: integer(2)
      unsigned: true
    expires_at:
      type: timestamp
  indexes:
    expires_at:
      fields: [ expires_at ]
  relations:
    Server:
      local: subnet
      foreign: id
      foreignAlias: Ips
      onDelete: CASCADE
      onUpdate: CASCADE
    Customer:
      local: customer_id
      foreign: id
      foreignAlias: Ips
      onDelete: SET NULL
      onUpdate: CASCADE