Order:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(5)
      unsigned: true
      notnull: true
      primary: true
      comment: "2CO order ID"
    sku:
      type: string(16)
      notnull: true
    customer_id:
      type: integer(2)
      unsigned: true
      notnull: true
    server_id:
      type: integer(1)
      unsigned: true
      comment: "Associated server"
    status:
      type: enum
      values: ['pending', 'approved', 'declined', 'refund']
      notnull: true
      default: 'pending'
  relations:
    Product:
      local: sku
      foreign: sku
      foreignAlias: Orders
      onDelete: CASCADE
      onUpdate: CASCADE
    Customer:
      local: customer_id
      foreign: id
      foreignAlias: Orders
      onDelete: CASCADE
      onUpdate: CASCADE
    Server:
      local: server_id
      foreign: id
      foreignAlias: Orders
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    status:
      fields: [status]
    time:
      fields: [created_at, updated_at]