Order:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    id:
      type: integer(5)
      unsigned: true
      notnull: true
      primary: true
      comment: "2CO order ID"
    sku:
      type: string(16)
      notnull: true
    customer_id:
      type: integer(2)
      unsigned: true
      notnull: true
  relations:
    Product:
      local: sku
      foreign: sku
      foreignAlias: Orders
      onDelete: CASCADE
      onUpdate: CASCADE
    Customer:
      local: customer_id
      foreign: id
      foreignAlias: Orders
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    created_at:
      fields: [created_at]