Product:
  columns:
    sku:
      type: varchar(16)
      notnull: true
      primary: true
      comment: "Must be started from VPN"
    2co_system_id:
      type: integer(5)
      unsigned: true
      notnull: true
      unique: true
      comment: "This id MUST be in sync with system product_id within 2co system"
    2co_assigned_id:
      type: integer(2)
      unsigned: true
      notnull: true
      unique: true
    title:
      type: string(100)
      notnull: true
    price:
      type: float(5)
      scale: 2
      unsigned: true
      notnull: true
