# used by radius
Server:
  columns:
    id:
      type: integer(1)
      unsigned: true
      primary: true
    hoster_id:
      type: integer(2)
      unsigned: true
      notnull: true
    hostname:
      type: varchar(64)
      notnull: true
      unique: true
    ip:
      type: varchar(15)
      notnull: true
      unique: true
      comment: "Required for radius. Must be unique to correctly allocate IPs."
    secret:
      type: char(16)
      notnull: true
      comment: "Shared secret to authenticate remote client"
    country:
      type: char(2)
      comment: "Country alpha-2 ISO code"
    city:
      type: varchar(32)
    datacenter:
      type: varchar(64)
    ram:
      type: integer(2)
      unsigned: true
      notnull: true
      default: 128
      comment: "in megabytes"
    storage:
      type: integer(2)
      unsigned: true
      comment: "in gigabytes; NULL for unlimited"
    transfer:
      type: integer(2)
      unsigned: true
      comment: "in gigabytes; NULL for unlimited"
    speed:
      type: integer(2)
      unsigned: true
      comment: "in mbps; NULL for unlimited/unknown"
    ips:
      type: integer(1)
      unsigned: true
      notnull: true
      default: 1
      comment: "number of ipv4 addresses"
    price:
      type: float(5)
      unsigned: true
      notnull: true
    virtualization:
      type: enum
      values: [ "openvz", "xen", "kvm", "dedicated" ]
      default: "openvz"
      notnull: true
    arch:
      type: enum
      values: [ 32, 64 ]
      default: 64
      notnull: true
    pptp:
      type: boolean
      notnull: true
      default: false
    openvpn:
      type: boolean
      notnull: true
      default: false
    is_active:
      type: boolean
      default: true
  relations:
    Hoster:
      local: hoster_id
      foreign: id
      foreignAlias: Servers
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    country:
      fields: [country]
