# used by radius
Server:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
      comment: "id is required for radius :("
    hostname:
      type: varchar(64)
      notnull: true
      unique: true
    secret:
      type: char(16)
      notnull: true
      comment: "Shared secret to authenticate remote client"
    country:
      type: char(2)
      comment: "Country alpha-2 ISO code"
    city:
      type: varchar(32)
    datacenter:
      type: varchar(64)
    is_active:
      type: boolean
      default: true
  indexes:
    country:
      fields: [country]
