# used by radius
Server:
  columns:
    id:
      type: integer(2)
      unsigned: true
      primary: true
      autoincrement: true
      comment: "id is required for radius :("
    hostname:
      type: string(50)
      notnull: true
      unique: true
    secret:
      type: char(16)
      notnull: true
      comment: "Shared secret to authenticate remote client"
    country:
      type: char(2)
      comment: "Country alpha-2 ISO code"
  indexes:
    country:
      fields: [country]